### ISSUE TITLE
Watch only for security releases

### ISSUE THREAD

**Issue by iBobik** [vfeskov/gitpunch#12]

**Comment by vfeskov** [comment]
can you please give an example of such release?

**Comment by iBobik** [comment]
Hmm. Can GitHub mark security release anyway? All I can find have it in a description, but I have not found any release with structured information about type of release.

What about loking for a keywords like: "security" or "CVE"?

**Comment by vfeskov** [comment]
@iBobik I'm thinking about allowing to set a pattern to look for in release description, because release name usually doesn't contain much info. 

This is a whole 'nother level of complexity though, since release descriptions haven't been loaded so far. On the other hand if i add this it would allow adding descriptions to emails too, which would be nice, but i wanna focus on simple stuff from other issues and on browser extensions first

**Comment by vfeskov** [comment]
so i gave it a lot of though and ultimately i think there's a lot of ongoing effort from github itself and, for example, npm to alert users when their projects have security vulnerabilities. I genuinely think it's better to rely on those alerts instead of release descriptions
