### ISSUE TITLE
Mute single repositories

### ISSUE THREAD

**Issue by NobbZ** [vfeskov/gitpunch#13]
Lets say I have maintain a list of watches and do not want to get disturbed during my holidays, but I want to still be notified about releases in two or three repositories that I consider security relevant.

With the current UI I have to delete all un-important repositories and then put them manually back when I'm back from my holidays.

**Comment by vfeskov** [comment]
To make emails less frequent (spammy) you can now subscribe to daily updates instead of hourly:
<img width="272" alt="screen shot 2018-01-30 at 19 04 00" src="https://user-images.githubusercontent.com/2743367/35582851-5d918754-05f0-11e8-862a-f0fc98bf2f0d.png">

----

To stop receiving emails when you're on vacation you can click this toggle:
<img width="151" alt="screen shot 2018-01-30 at 19 04 35" src="https://user-images.githubusercontent.com/2743367/35582898-7c55a90e-05f0-11e8-8437-0bebf219782c.png">
And when you return from vacation you can click the toggle again, re-subscribe and it will send you all updates that you weren't notified of since you were last subscribed.

----

What do you think, are these options enough? I think separate list of important repos is going to complicate user experience tremendously and I'd really rather not do it

**Comment by NobbZ** [comment]
It were just a switch per repo instead of a global one. And my workflow
especially states that I want (or maybe need to) receive updates for
certain repositories ASAP.

But making the controls more fine-grained is a good start. I like that,
regardless if it helps me with this issue.

Vladimir Feskov <notifications@github.com> schrieb am Di., 30. Jan. 2018,
19:13:

**Comment by vfeskov** [comment]
hm actually adding a mute button next to a repo wouldn't be too bad, i'll work on it

**Comment by vfeskov** [comment]
@NobbZ i just had an idea, `winabeer` supports signing up by email, right? so you can have multiple accounts like `nobbz+important@gmail.com` and `nobbz+meh@gmail.com`, and each can be subscribed to corresponding repos: one to important/urgent and the other to not-so-important. Then you can unsubscribe on not-so-important account.

I feel like it might be a bit cumbersome but ultimately super flexible because you can have as many separate repo lists as you want. i'm not abandoning this task of course, but wanna know your opinion about this. i think i'll document it anyway

**Comment by AlexWayfer** [comment]
> so you can have multiple accounts like nobbz+important@gmail.com and nobbz+meh@gmail.com, and each can be subscribed to corresponding repos: one to important/urgent and the other to not-so-important. Then you can unsubscribe on not-so-important account when you're on vacation.

It doesn't work with every email provider.
