### ISSUE TITLE
Small improvement: add a simple Table of content in the E-Mails?

### ISSUE THREAD

**Issue by schittli** [vfeskov/gitpunch#38]
Good morning

### I have just a small suggestion:
it would be great if the E-Mail Body could have a simple Table of content, the items must not be clickable. Just some text so that we can get an overview if there are a lot of items and the subject is not long enough. For example:

- **ClassOutline**, 2017.2
- **codemaid**, 10.5
- **WebJEA**, 0.9.149
- **Humanizer**, 2.3.3
- **moq4**, 4.8.3
- **mfcmapi**, 18.2.18160.129
- **platyPS**, 0.10.0

#### btw.: please don't print the version number in bold, 
because the first eye catcher should be the Software name, because the version number itself does not help at all.

Therefore, something like this would be much more readable:
- stephenegriffin: **mfcmapi**, 18.2.18160.129

than
- stephenegriffin/mfcmapi@**18.2.18160.129**

Thanks a lot for all your work and support,
kind regards,
Thomas

**Comment by TPS** [comment]
Maybe this could _optionally_ replace what looks to be the e-mail subject, for those who prefer this?

**Comment by vfeskov** [comment]
made it so that if there are more than 1 release, it will show a ToC in the beginning of email:

<img width="1063" alt="screen shot 2018-07-15 at 11 16 46" src="https://user-images.githubusercontent.com/2743367/42732371-9cce2c08-8820-11e8-8bf5-791b5114de3f.png">

also sort repo names alphabetically now
