### ISSUE TITLE
Receive each mail twice

### ISSUE THREAD

**Issue by sdouche** [vfeskov/gitpunch#63]
Hi :)
Since Jan 6, I receive the email twice.

![screenshot-www fastmail com-2019 01 08-11-19-09](https://user-images.githubusercontent.com/170176/50826317-91b3f900-133b-11e9-8f66-33be73aa6d54.png)

Regards.

**Comment by vfeskov** [comment]
Hi Sébastien, you have two accounts on GitPunch, both linked to your GitHub account. I assume you changed your GitHub email and signed in to GitPunch using the new email so it registered you again instead of signing you in your old account. What you can do yourself is to find one email that is sent to your old email address and click "unsubscribe" in it. I can also delete the wrong account, send its name to me over email please: v at vladimirfeskov.com

**Comment by sdouche** [comment]
Hi @vfeskov. You're right, I switched to a new email. I followed your advice and removed notifications from my old email. Thanks!
