### ISSUE TITLE
Updates missing in email

### ISSUE THREAD

**Issue by Archinowsk** [vfeskov/gitpunch#94]
For the past four days, the daily emails have had only 1-2 projects with updated versions. I have 1.4k starred projects and usually, there are 10-20 updated projects in each email. 

For example, a new version of [Jest](https://github.com/facebook/jest/releases/tag/v25.2.3) was released 26.3. and it was missing from the email.

Thanks for offering this extremely useful service!

25.3.

![image](https://user-images.githubusercontent.com/1327412/77851685-17db8a00-71e3-11ea-88c3-9b8d6ffde225.png)

26.3.

![image](https://user-images.githubusercontent.com/1327412/77851696-23c74c00-71e3-11ea-8670-73648d4d30f4.png)

27.3.

![image](https://user-images.githubusercontent.com/1327412/77851699-2d50b400-71e3-11ea-9151-71a2a4c1c761.png)

28.3.

![image](https://user-images.githubusercontent.com/1327412/77851709-35a8ef00-71e3-11ea-863a-1758bdbfe36e.png)

29.3.

![image](https://user-images.githubusercontent.com/1327412/77851717-3d689380-71e3-11ea-9eb2-bb8d08ec114f.png)

**Comment by vfeskov** [comment]
can you please email me your user's email address, my email is v@vladimirfeskov.com

**Comment by vfeskov** [comment]
Looks like github introduced a limit of 1 concurrent request per host on 25th March, before that a 100 were working just fine

Daily emails are made by requesting releases of all repositories of all the relevant users from atom feeds, e.g., https://github.com/vfeskov/gitpunch/tags.atom . 

For example, there were 100 users with 30 000 unique repositories in total, and they all were subscribed to receive an email at 09:00 UTC, and the time was 09:00 UTC.
The notifier script would load tags of each of the 30 000 repositories, running 100 groups in parallel, each group requesting 300 repos sequentially, effectively maintaining 100 concurrent requests

Now after ~500 requests loaded this way github starts rejecting any further requests, and it only allows to continue if I request 1 repo at a time.

Changing concurrent requests limit to just 1 drastically increased script execution time and it no longer fits in 15 minutes limit of AWS Lambda, which I use to run the script

It will take time to fix this properly since I'm employed full-time, but it will be fixed ASAP

In the meantime, you can switch to realtime emails - those rely mainly on [release events](https://developer.github.com/v3/activity/events/) and only use the now broken "load-all" strategy as a backup

**Comment by szpak** [comment]
FYI @vfeskov, in a case you are working on that. Today I've got a batch mail with **a lot of** project notifications (it's hard to say it it was all, but definitely it is more than I used to get on a daily basis in the past).

**Comment by vfeskov** [comment]
i think it's fixed, im going to monitor for a few days before closing the issue - please leave a comment if you have any problems still

will explain what i did in a release note

**Comment by vfeskov** [comment]
alright so everything looks good on my side and no complaints here either so im gonna close
